version: '3.8'

services:
  db:
    image: postgres:16
    container_name: event_db
    env_file:
      - .env
    ports:
      - 5432:5432
  
  event_parser:
    image: parser_image
    build: 
      context: .
    container_name: parser
    env_file:
      - .env
    depends_on:
      - db
    command: [/event_parser/docker/start.sh]