"""Initial migration

Revision ID: eb3c4e386685
Revises: 
Create Date: 2024-07-07 21:58:10.333134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3c4e386685'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('killer_id', sa.Integer(), nullable=True),
    sa.Column('victim_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('group_member_count', sa.Integer(), nullable=True),
    sa.Column('gvg_match', sa.Boolean(), nullable=True),
    sa.Column('kill_area', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('guild_name', sa.String(), nullable=True),
    sa.Column('alliance_name', sa.String(), nullable=True),
    sa.Column('kill_fame', sa.String(), nullable=True),
    sa.Column('average_itemPower', sa.Integer(), nullable=True),
    sa.Column('main_Hand', sa.String(), nullable=True),
    sa.Column('off_hand', sa.String(), nullable=True),
    sa.Column('head', sa.String(), nullable=True),
    sa.Column('armor', sa.String(), nullable=True),
    sa.Column('shoes', sa.String(), nullable=True),
    sa.Column('bag', sa.String(), nullable=True),
    sa.Column('cape', sa.String(), nullable=True),
    sa.Column('mount', sa.String(), nullable=True),
    sa.Column('potion', sa.String(), nullable=True),
    sa.Column('food', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('events')
    # ### end Alembic commands ###
